name: Deploy Medical Chatbot to AWS EC2 using ECR

on:
  push:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t medibot .

      - name: Tag Docker image
        run: docker tag medibot:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push image to ECR
        run: docker push ${{ secrets.ECR_REPO }}:latest


  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop medibot || true
            docker rm medibot || true

            aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

            docker pull ${{ secrets.ECR_REPO }}:latest

            docker run -d -p 8080:8080 \
              -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
              -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              --name medibot \
              ${{ secrets.ECR_REPO }}:latest